# IMPORTING LYBRARIES

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# DATA LOADING

In [24]:
df =pd.read_csv('C:\\Users\\chara\\OneDrive\\Desktop\\LPP\\Laptop_price.csv')

# DATA UNDERSTANDING

In [25]:
df.head()

,Brand,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
0,Asus,3.830296,16,512,11.185147,2.641094,17395.093065
1,Acer,2.912833,4,1000,11.311372,3.260012,31607.605919
2,Lenovo,3.241627,4,256,11.853023,2.029061,9291.023542
3,Acer,3.806248,16,512,12.280360,4.573865,17436.728334
4,Acer,3.268097,32,1000,14.990877,4.193472,32917.990718

In [26]:
df.tail()

,Brand,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
995,HP,3.343584,4,1000,12.587095,3.162399,31593.668017
996,Dell,2.780555,8,256,12.679356,3.750265,9149.521832
997,Dell,3.200569,4,512,12.666315,3.392612,16552.404779
998,Asus,1.604182,8,256,11.215581,3.857613,9407.473459
999,Lenovo,1.711980,4,256,16.561498,3.440883,8807.696702

In [27]:
df.shape

(1000, 7)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             1000 non-null   object
 1   Processor_Speed   1000 non-null   float64
 2   RAM_Size          1000 non-null   int64
 3   Storage_Capacity  1000 non-null   int64
 4   Screen_Size       1000 non-null   float64
 5   Weight            1000 non-null   float64
 6   Price             1000 non-null   float64
dtypes: float64(4), int64(2), object(1)
memory usage: 54.8+ KB

In [29]:
df.describe()

,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2.750611,15.500000,584.576000,14.056790,3.466919,19604.187963
std,0.731796,10.988665,313.438517,1.705882,0.866541,9406.064880
min,1.511580,4.000000,256.000000,11.012111,2.000560,8570.012950
25%,2.089246,8.000000,256.000000,12.635523,2.717211,10114.012948
50%,2.760885,16.000000,512.000000,14.099643,3.464630,17287.241878
75%,3.362610,32.000000,1000.000000,15.528590,4.212583,31566.214754
max,3.998534,32.000000,1000.000000,16.985737,4.990728,33503.935037

# DATA PREPROCESSING

### NULL VALUES

In [30]:
# check null values
df.isnull().sum()

# remove null values (if any)
df = df.dropna()

### DUPLICATE VALUES

In [31]:
# check duplicates
df.duplicated().sum()

# remove duplicates
df = df.drop_duplicates()

### UNNAMED COLUMNS

In [32]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

### DATA CONVERSTION

In [33]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Brand'] = le.fit_transform(df['Brand'])

# FEATURE TRANSFORMATION

In [34]:
# example new feature
df['Performance_Index'] = df['Processor_Speed'] * df['RAM_Size']

# FEATURE SELECTION

In [35]:
X = df.drop('Price', axis=1)   # input features
y = df['Price']                # output

# FEATURE SCALING

### STANDERDIZATION

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

### NORMALIZATION

In [37]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# SPLITTING DATA

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# MODEL SELECTION

In [39]:
# Import required libraries
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score

# Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

# SVM Model
svm = SVR()
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)

# Decision Tree Model
dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

# Random Forest Model
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

# Polynomial Regression
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)
poly_pred = poly_model.predict(X_test_poly)

# Print R2 Scores of all models
print("Linear Regression R2 Score:", r2_score(y_test, lr_pred))
print("SVM R2 Score:", r2_score(y_test, svm_pred))
print("Decision Tree R2 Score:", r2_score(y_test, dt_pred))
print("Random Forest R2 Score:", r2_score(y_test, rf_pred))
print("Polynomial Regression R2 Score:", r2_score(y_test, poly_pred))

Linear Regression R2 Score: 0.9996454189992813
SVM R2 Score: -0.036790088186349656
Decision Tree R2 Score: 0.9991769656471395
Random Forest R2 Score: 0.9995559842977814
Polynomial Regression R2 Score: 0.999635940991514

### model prediction

In [40]:
import pandas as pd

y_pred = lr.predict(X_test)

results = pd.DataFrame({
    "Actual_Price": y_test,
    "Predicted_Price": y_pred
})

print(results.head(10))

     Actual_Price  Predicted_Price
521  10900.502075     10759.360272
737  31727.516697     31564.265578
740   9636.022750      9635.423215
660   9412.599857      9240.152093
411  31641.105861     32017.063264
678  31832.486943     31653.290235
626  10438.451568     10303.295929
513  17205.205679     16943.370776
859  18743.569392     18506.808818
136  32342.705862     32365.018942

### SAVE MODEL

In [41]:
import pickle

with open("model.pkl", "wb") as f:
    lr = LinearRegression()
    lr.fit(X_train, y_train)
    pickle.dump(lr, f)

In [42]:
import pickle
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

print("Model and scaler saved successfully")

Model and scaler saved successfully